# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
  
    steps:
      - checkout
      - run: mvn compile
      - run: mvn test
      - store_artifacts:
           path: target/surefire-reports/junitreports/
      - store_test_results:
          path: target/surefire-reports/junitreports/
     
        
    
